### ISSUE TITLE
Automated Test Coverage

### ISSUE THREAD

**Issue by sebgro98** [boolean-uk/team-dev-server-ex-2410-team3#6]
# Automated Test Coveredge

The realistically achievable code coverage is in this case deemed to be 50% (initial value open to change) as there are multiple aspects considered to be key areas for the project. 
The tests should provide a balance between high coverage and quality. Relying too heavily on mockup data might give a false sense of security.  This will be implemented using C8, a code coverage tool for JavaScript.

### Step 1: install ``c8``
`` npm install --save-dev c8``

### Step 2: Configure ``c8`` in package.json
```
"scripts": {
  "test": "jasmine",
  "test:coverage": "c8 jasmine"
},
"c8": {
  "reporter": ["text", "lcov"],
  "all": true,
  "include": ["src/**/*.js"], // Include files in the src folder
  "exclude": ["**/spec/**"],   // Exclude test files from coverage
  "check-coverage": true,
  "statements": 50, // Minimum coverage thresholds
  "branches": 50,
  "functions": 50,
  "lines": 50
}
```

### Step 3: Run Test Coverage Locally
``npm run test:coverage``

### Step 4: Set Up GitHub Actions for Automated Coverage Reporting
In the ``.github/workflows/test.yml`` configure the following: 

```
name: Run Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
```
